version: '3'

services:

  superhero-dashboard:
    image: superhero-dashboard:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      BACKEND_URL: https://beta.schul-cloud.org:8080/
    networks:
      - default
    ports:
      - 3033:3033
    volumes:
      - .:/app
    command: npm run start