version: '3'

services:

  superhero-dashboard:
    image: superhero-dashboard:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      BACKEND_URL: https://schul-cloud.org:8080/
      SC_NAV_TITLE: 
      HOST: 
      SC_THEME: 
    networks:
      - default
    ports:
      - 3033:3033
    volumes:
      - .:/app
    command: npm run start
